
name: Android Native build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Install Android NDK
      if: steps.check_submodule.outputs.trigger_build == 'true'
      uses: nttld/setup-ndk@v1.4.2
      with:
        ndk-version: r25c

    - name: Run android build
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make android
