
name: MacOs Native build

on:
  workflow_dispatch: 


jobs:
  intel-build:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Run apple coreml build for x64
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_coreml_x64

    - name: Run apple build for x64
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_x64
      
  arm-build:
    needs: intel-build
    runs-on: macos-14
    permissions:
       contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}

    - name: Run apple build for arm
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_arm

    - name: Run apple coreml build for arm
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_coreml_arm
