
name: MacOs Native build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  intel-build:
    runs-on: macos-13
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Check for submodule update
      id: check_submodule
      run: |
        cd whisper.cpp
        SUBMODULE_COMMIT_ID=$(git rev-parse HEAD)
        echo "Submodule commit ID: $SUBMODULE_COMMIT_ID"
        cd $GITHUB_WORKSPACE
        STORED_COMMIT_ID=$(cat native-commit-id-macos-x64)
        echo "Stored commit ID: $STORED_COMMIT_ID"
        if [ "$SUBMODULE_COMMIT_ID" != "$STORED_COMMIT_ID" ]; then
          echo "Submodule has new commits. Triggering build."
          echo "trigger_build=true" >> $GITHUB_OUTPUT
          echo $SUBMODULE_COMMIT_ID > native-commit-id-macos-x64
        else
          echo "No new commits in submodule."
          echo "trigger_build=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Run apple coreml build for x64
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_coreml_x64

    - name: Run apple build for x64
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_x64

    - name: Pull latest commits
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: git pull origin ${{ github.head_ref }}

    - name: Commit and Push
      if: steps.check_submodule.outputs.trigger_build == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add native changes macos

  arm-build:
    depends-on: intel-build
    runs-on: macos-14
    permissions:
       contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    - name: Check for submodule update
      id: check_submodule
      run: |
        cd whisper.cpp
        SUBMODULE_COMMIT_ID=$(git rev-parse HEAD)
        echo "Submodule commit ID: $SUBMODULE_COMMIT_ID"
        cd $GITHUB_WORKSPACE
        STORED_COMMIT_ID=$(cat native-commit-id-macos-arm)
        echo "Stored commit ID: $STORED_COMMIT_ID"
        if [ "$SUBMODULE_COMMIT_ID" != "$STORED_COMMIT_ID" ]; then
          echo "Submodule has new commits. Triggering build."
          echo "trigger_build=true" >> $GITHUB_OUTPUT
          echo $SUBMODULE_COMMIT_ID > native-commit-id-macos-arm
        else
          echo "No new commits in submodule."
          echo "trigger_build=false" >> $GITHUB_OUTPUT
        fi

    - name: Run apple coreml build for arm
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_coreml_arm

    - name: Run apple build for arm
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make apple_arm

    - name: Pull latest commits
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: git pull origin ${{ github.head_ref }}

    - name: Commit and Push
      if: steps.check_submodule.outputs.trigger_build == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add native changes macos