
name: Wasm Native build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v13
   
    - name: Run wasm build
      run: make wasm

    - name: Remove Emscripten
      run: rm -rf emsdk*
      
    - name: Upload Wasm Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-build
        path: 'Whisper.net.Run*/browser-wasm/*'
