
name: Wasm Native build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        ref: ${{ github.head_ref }}
    
    - name: Install Emscripten
      if: steps.check_submodule.outputs.trigger_build == 'true'
      uses: mymindstorm/setup-emsdk@v13
   
    - name: Run wasm build
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: make wasm

    - name: Remove Emscripten
      if: steps.check_submodule.outputs.trigger_build == 'true'
      run: rm -rf emsdk*
      
