name: Windows native build

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-2019
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
  
        with:
          submodules: true
          ref: ${{ github.head_ref }}
          
      - name: Add msbuild to PATH
        if: steps.check_submodule.outputs.trigger_build == 'true'
        uses: microsoft/setup-msbuild@v1
        
      # - name: Install OpenCl with vcpkg
      #   if: steps.check_submodule.outputs.trigger_build == 'true'
      #   run: |
      #      vcpkg --triplet=x64-windows install opencl

      # - name: Install CUDA Toolkit
      #   if: steps.check_submodule.outputs.trigger_build == 'true'
      #   uses: Jimver/cuda-toolkit@v0.2.11
      #   with:
      #     cuda: '12.1.0'

      - name: Run Build
        if: steps.check_submodule.outputs.trigger_build == 'true'
        run: | 
          Import-Module ./windows-scripts.ps1
          BuildWindowsIntel
        shell: pwsh

      # - name: Remove CUDA installer
      #   if: steps.check_submodule.outputs.trigger_build == 'true'
      #   run: Remove-Item -Path 'cuda_installer-*' -Recurse -Force -ErrorAction Ignore

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: 'Whisper.net.Runtime/win-*/*'
