name: Windows ARM native build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 


jobs:
  build:

    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}
          
      - name: Add msbuild to PATH
        if: steps.check_submodule.outputs.trigger_build == 'true'
        uses: microsoft/setup-msbuild@v1
        
      - name: Run Build
        if: steps.check_submodule.outputs.trigger_build == 'true'
        run: | 
          Import-Module ./windows-scripts.ps1
          BuildWindowsArm
        shell: pwsh

      - name: Remove CUDA installer
        if: steps.check_submodule.outputs.trigger_build == 'true'
        run: Remove-Item -Path 'cuda_installer-*' -Recurse -Force -ErrorAction Ignore
