name: Windows ARM native build

on:
  workflow_dispatch: 


jobs:
  build:

    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}
